version: '3.8'

services:
  admin-service:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    container_name: littlebook_admin
    ports:
      - "8085:8085"
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: littlebook_auth
    ports:
      - "8081:8081"
    environment:
      - FIREBASE_CREDENTIALS=/app/littlebook.json
      - FIREBASE_PROJECT_ID=littlebook-b2d2d
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./littlebook.json:/app/littlebook.json:ro
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: littlebook_user
    ports:
      - "8082:8082"
    restart: unless-stopped

  review-service:
    build:
      context: .
      dockerfile: review-service/Dockerfile
    container_name: littlebook_review
    ports:
      - "8083:8083"
    restart: unless-stopped
  book-service:
    build:
      context: .
      dockerfile: book-service/Dockerfile
    container_name: littlebook_book
    ports:
      - "8084:8084"
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: littlebook_gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.epgxaozzqwdlbwtuefye.supabase.co:5432/postgres?sslmode=require
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Need2eatandsleep@diner
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS:-}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-littlebook-b2d2d}
    restart: unless-stopped



