version: '3.8'

services:
  admin-service:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    container_name: littlebook_admin
    ports:
      - "8082:8082"
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: littlebook_auth
    ports:
      - "8081:8081"
    environment:
      - FIREBASE_CREDENTIALS=/app/littlebook.json
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: littlebook_user
    ports:
      - "8083:8083"
    restart: unless-stopped

