spring:
  application:
    name: littlebook-back

  main:
    banner-mode: console # garde l’affichage de la bannière Spring Boot
    lazy-initialization: false # charge tout au démarrage (bon pour dev)

  output:
    ansi:
      enabled: always # couleurs dans la console

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.epgxaozzqwdlbwtuefye
    password: Need2eatandsleep@diner
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080 # port du serveur
  error:
    include-message: always # utile pour debug les erreurs

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  firebase: # config Firebase
    credentials-path: ${FIREBASE_CREDENTIALS}
    project-id: ${FIREBASE_PROJECT_ID}
